// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './type';

export const SUPABASE_URL = "https://spb-t4n28pv11dt9m5pb.supabase.opentrust.net";
export const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG4yOHB2MTFkdDltNXBiIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NzczODk3OTQsImV4cCI6MjA5Mjk2NTc5NH0.6tYn-5pM3LKMSgpOlfpChQKSzU5D9lNVNvD4LK3mqas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});
